### ISSUE TITLE
some errors about apt-get and npm in your docker

### ISSUE THREAD

**Issue by changemenemo** [hexparrot/mineos-docker#4]
Is npm installed by node ? 
because I've got this: 

`The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends:
: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

that was with apt-get install npm 

And I've updated node.js in my container and when I tried to run reset_webui.sh I've got this:

`Updating mineos-node repository...OK
Checking out master branch...Already on 'master'
OK
Resetting directory to official contents...OK
Deleting npm module dependencies and rebuilding...npm WARN engine apache-crypt@1.1.2: wanted: {"node":">=5"} (current: {"node":"4.5.0","npm":"2.15.9"})
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
OK
Setting node javascript files to executable...OK
Script execution ended on: Sat Aug 20 22:28:16 UTC 2016
root@72b34d72f549:/usr/games/minecraft# ./update_webui.sh`

**Comment by hexparrot** [comment]
npm isn't installed via apt-get, but instead by downloading the .deb package file directly and then installing it.

https://github.com/hexparrot/mineos-docker/blob/master/debian-jessie/Dockerfile#L20

Nodesource creates the most stable, available, and reliably-scriptable packages I've seen, and it is distro-agnostic (compared to just apt-get), so npm is _not_ installed by apt-get and these conflicts from apt-get are expected.

**Comment by changemenemo** [comment]
Mmmmmh ok I wasn’t sure that it was aprt of the question, so that’s the reason of my stupid question sorry 😊 
And the hypothetical warn of npm when I update the ui is it the same reason ?

Also, we should find a regex expression or something equivalent to download the latest deb instead of a fixed vesion in the dockerfile no ?

**Comment by boistordu** [comment]
and i've try jsut now to only do a reset_webui, since your dockerfile is not up to date for the node.deb, we received these kind of errors: 
`Deleting npm module dependencies and rebuilding...WARN engine apache-crypt@1.1.2: wanted: {"node":">=5"} (current: {"node":"4.3.1","npm":"2.14.12"})
WARN engine angular-translate@2.11.1: wanted: {"node":">=4.4"} (current: {"node":"4.3.1","npm":"2.14.12"})
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/games/minecraft/node_modules/posix
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/games/minecraft/node_modules/userid
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-spin"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! posix@4.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix@4.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the posix package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls posix
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/games/minecraft/npm-debug.log
FAILED`

**Comment by hexparrot** [comment]
> And the hypothetical warn of npm when I update the ui is it the same reason ?

Warnings are just warnings and not errors, so it's something we can deal with; I'm not particularly concerned about them as they're usually very mild in effect and I've never seen any adverse behaviors as a result.

> Also, we should find a regex expression or something equivalent to download the latest deb instead of a fixed vesion in the dockerfile no ?

It could be possible to poll nodesource and to determine a version dynamically, though the problem arises that it no longer makes the Dockerfile create a consistent environment; anytime somebody builds, they could be greeted with a completely different version that may or may not have broken something in MineOS.  At least when it's hard coded, while it has the downside of not being _the absolutely most current_, it does have the benefit of having been tested before it was committed to the repo.
